apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: janus-testnet-volume
  name: janus-testnet-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
status: {}
