apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: qtum-testnet-volume
  name: qtum-testnet-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
status: {}
